name = "clg-mcp"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true

[build]
command = "npm run build"

# Production environment
[env.production]
name = "clg-mcp"

[env.production.vars]
DEBUG_MODE = "false"
ENVIRONMENT = "production"
MCP_SERVER_NAME = "clg-mcp"
MCP_SERVER_VERSION = "1.0.0"
REQUEST_TIMEOUT = "30000"
MAX_SEARCH_RESULTS = "50"
MCP_PROTOCOL_VERSION = "2024-11-05"
USER_AGENT = "CLG-MCP/1.0.0 (Genealogy Research Tool)"
# SSE Configuration
SSE_ENABLED = "true"
SSE_HEARTBEAT_INTERVAL = "30000"
SSE_MAX_CONNECTIONS = "100"
# Authentication tokens should be set as secrets, not vars
# Single token: wrangler secret put MCP_AUTH_TOKEN
# Multiple tokens: wrangler secret put MCP_AUTH_TOKENS (comma-separated)
# See AUTHENTICATION.md for detailed setup instructions

# Development environment
[env.development]
name = "clg-mcp-dev"

[env.development.vars]
DEBUG_MODE = "true"
ENVIRONMENT = "development"
MCP_SERVER_NAME = "clg-mcp-dev"
MCP_SERVER_VERSION = "1.0.0"
REQUEST_TIMEOUT = "30000"
MAX_SEARCH_RESULTS = "50"
MCP_PROTOCOL_VERSION = "2024-11-05"
USER_AGENT = "CLG-MCP/1.0.0 (Genealogy Research Tool)"
# SSE Configuration
SSE_ENABLED = "true"
SSE_HEARTBEAT_INTERVAL = "30000"
SSE_MAX_CONNECTIONS = "100"
# Authentication tokens should be set as secrets, not vars
# Single token: wrangler secret put MCP_AUTH_TOKEN --env development
# Multiple tokens: wrangler secret put MCP_AUTH_TOKENS --env development
# See AUTHENTICATION.md for detailed setup instructions

# Global variables (default/fallback)
[vars]
DEBUG_MODE = "false"
REQUEST_TIMEOUT = "30000"
MAX_SEARCH_RESULTS = "50"
MCP_PROTOCOL_VERSION = "2024-11-05"
USER_AGENT = "CLG-MCP/1.0.0 (Genealogy Research Tool)"
# SSE Configuration
SSE_ENABLED = "true"
SSE_HEARTBEAT_INTERVAL = "30000"
SSE_MAX_CONNECTIONS = "100"